apiVersion: v1
kind: Service
metadata:
  name: walshsoft-service
spec:
  type: LoadBalancer  # Set to NodePort when using SSL
  selector:
    app: walshsoft-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
