apiVersion: v1
kind: Service
metadata:
  name: walshsoft-service
spec:
  type: NodePort  # Set to LoadBalancer when no SSL/ingress
  selector:
    app: walshsoft-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
