sudo: required

language: python

python:
  - 3.6

services:
  - docker

install:
  - pip install -r requirements.txt

before_install:
- docker build -t mattthinkwhere/walshsoft .
- docker run -d -p 8000:8000 mattthinkwhere/walshsoft