sudo: false

# Cache Gcloud SDK between commands
cache:
  directories:
    - "$HOME/google-cloud-sdk/"

services:
  - docker

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME=walshsoft-218612
    - CLUSTER_NAME=walshsoft-cluster
    - CLOUDSDK_COMPUTE_ZONE=europe-north1-a
    - NGINX_DOCKER_IMAGE_NAME=nginx
    - WEB_DOCKER_IMAGE_NAME=web
    - KUBE_DEPLOYMENT_NAME=walshsoft-service
    - KUBE_DEPLOYMENT_CONTAINER_NAME=appexample

script:
  - docker build --quiet -t gcr.io/${PROJECT_NAME}/${WEB_DOCKER_IMAGE_NAME}:$TRAVIS_COMMIT web/
  - docker build --quiet -t gcr.io/${PROJECT_NAME}/${NGINX_DOCKER_IMAGE_NAME}:$TRAVIS_COMMIT nginx/

# Run unit tests
  - docker run --rm --name web gcr.io/${PROJECT_NAME}/${WEB_DOCKER_IMAGE_NAME}:$TRAVIS_COMMIT /bin/sh -c "python manage.py test postcode_api/tests/tests_unit"
  # Run integration tests against docker host
  - docker run --name web gcr.io/${PROJECT_NAME}/${WEB_DOCKER_IMAGE_NAME}:$TRAVIS_COMMIT /bin/sh -c "gunicorn walshsoft.wsgi:application --bind :8000"
  - docker run --rm --name web --env POSTCODE_HOST=web gcr.io/${PROJECT_NAME}/${WEB_DOCKER_IMAGE_NAME}:$TRAVIS_COMMIT /bin/sh -c "pytest web/postcode_api/tests/tests_integration && pip freeze"

before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: ./devops/deploy.sh
    skip_cleanup: true
    on:
      branch: master
