sudo: required

services:
  - docker

install:
  - docker-compose build

script:
  - docker-compose run

#before_script:
#  - python manage.py migrate
#script:
#  - python manage.py test

#before_install:
#- docker build -t mattthinkwhere/walshsoft .
#- docker run -d -p 8000:8000 mattthinkwhere/walshsoft