sudo: required

language: python

services:
  - docker

before_install:
- docker build -t mattthinkwhere/walshsoft .
- docker run -d -p 8000:8000 mattthinkwhere/walshsoft
- docker ps -a
#- docker run mattthinkwhere/walshsoft /bin/sh -c "cd /root/walshsoft; bundle exec rake test"

#script:
#- bundle exec rake test